<?php
/**
 * @file
 * Code for the CRF Contacts Upload feature.
 */

include_once 'crf_contacts_upload.features.inc';


/**
 * Implements hook_node_insert().
 */
function crf_contacts_upload_node_insert($node) {
  if ($node->type == 'contact' && $node->is_new) {
    // Add information focal point to cluster term
    // on creation of a new contact.
    $clusters = $node->field_clusters['und'];
    if (!empty($clusters)) {
      foreach ($clusters as $item) {
        $cluster_term = taxonomy_term_load($item['tid']);
        $cluster_term->field_information_focal_points['und'][]['target_id'] = $node->nid;
        taxonomy_term_save($cluster_term);
      }
    }
  }
}


/**
 * Implements hook_form_FORM_ID_alter().
 */
function crf_contacts_upload_form_contacts_upload_node_form_alter(&$form, &$form_state, $form_id) {
  if (module_exists('entityconnect')) {
    unset($form['field_crf_request']['add_entityconnect__field_crf_request_all_']);
    unset($form['field_crf_request']['edit_entityconnect__field_crf_request_all_']);
  }
  
  $cluster_tid = isset($_GET['edit']['field_cluster']['und']) ? $_GET['edit']['field_cluster']['und'] : NULL;
  
  $form['existing_contacts'] = array(
    '#type' => 'fieldset',
    '#title' => t('Existing contacts'),
    '#weight' => 10,
  );
  $form['existing_contacts']['contacts_view'] = array(
    '#type' => 'item',
    '#markup' => views_embed_view('contacts', 'page_2', $cluster_tid),
    '#prefix' => t('You can see what contacts we already have by searching below.'),
  );
  
  $node = $form['#node'];
  if (!isset($node->nid)) {  
    $form['actions']['submit']['#value'] = t('Submit to OCHA');
  }
}




